all:
	
6.2-1c:
	javac Main.java
	java Main -i 6.2-1c.txt -m GESP

7.3-1a:
	javac Main.java
	java Main -i 7.3-1a.txt -m JCB

7.3-1b:
	javac Main.java
	java Main -i 7.3-1b.txt -m JCB

clean:
	rm *.class
